import type { PresetStory } from "./presetStorySchema.js";

type PresetMessage = PresetStory["messages"][number];

const m = (
  roleId: string,
  text: string,
  options: Omit<PresetMessage, "roleId" | "text"> = {}
): PresetMessage => ({ roleId, text, ...options });

export const viralPresetStories: PresetStory[] = [
  {
    id: "viral-pan-jinlian-window-request",
    title: "你上楼拦我吗",
    viralRole: "male",
    characterNames: { boy: "武松", girl: "潘金莲" },
    prompt: "武大郎外出卖饼，潘金莲深夜告诉武松有人要来，还故意问他会不会上楼阻止。武松怀疑她要与西门庆私会，却在追问中暴露自己不只是替哥哥担心；潘金莲也把试探逼到“你拦我是为你哥，还是为你自己”。",
    nextPrompt: "第三次敲门后，潘金莲可以真的开门，也可以揭穿这只是她逼武松表态的局；下一段可让西门庆发来定位、武大郎突然回家，或让武松终于上楼确认门后是谁。",
    messages: [
      m("girl", "二郎，你哥今晚不回来了。"),
      m("boy", "哥哥让我来送酒。"),
      m("girl", "放门口就好，别上楼。"),
      m("boy", "嫂嫂屋里有人？"),
      m("girl", "现在没有，待会儿就不好说了。"),
      m("boy", "西门庆要来？"),
      m("girl", "你这么快说出他的名字，是盯着他，还是盯着我？"),
      m("boy", "我怕他坏了哥哥的名声。"),
      m("girl", "只怕你哥的名声？"),
      m("boy", "不然还能为什么。"),
      m("girl", "若我今夜真想让别的男人上楼呢？"),
      m("boy", "嫂嫂自重。"),
      m("girl", "你若真不在意，何必回得这么快。"),
      m("boy", "我只问那个人是谁。"),
      m("girl", "那你希望是谁？"),
      m("boy", "不是我该希望的事。"),
      m("girl", "那我就开门给西门大官人。"),
      m("boy", "你敢。"),
      m("girl", "这句话像替哥哥说的，还是你自己说的？"),
      m("boy", "你一直在激我。"),
      m("girl", "是。我只是想看看，若我真越一次墙，你会不会拦我。"),
      m("boy", "我替哥哥拦。"),
      m("girl", "只替你哥？"),
      m("girl", "门外有人敲了三下。"),
      m("boy", "别开门。"),
      m("girl", "那你上楼拦我。"),
      m("boy", "我就在楼下。"),
      m("girl", "我知道。从你说送酒开始，我就在窗边看你。"),
      m("boy", "那门外的人是谁？"),
      m("girl", "你上来，我就告诉你。")
    ]
  },
  {
    id: "viral-trump-takaichi-tariff-coupon",
    title: "特朗普的关税优惠券",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "特朗普", girl: "高市早苗" },
    prompt: "特朗普给高市早苗发了一张亲笔签名的“关税优惠券”，高市早苗问他能不能和会员折扣叠加使用。",
    nextPrompt: "高市把优惠券发进多国群聊后意外引来竞价，特朗普开始追查条款是谁泄露的；故事可以走外交拍卖、会员体系失控或假券风波。",
    messages: [
      m("boy", "送你一张最好的关税优惠券。"),
      m("girl", "可以和会员折扣叠加吗？"),
      m("boy", "仅限当面使用。"),
      m("girl", "还要满额吗？"),
      m("boy", "满额才显得优惠。"),
      m("girl", "券上怎么没有截止日期？"),
      m("boy", "谈判结束那天自动过期。"),
      m("girl", "谁决定谈判结束？"),
      m("boy", "我。"),
      m("girl", "那折扣到底是多少？"),
      m("boy", "看你买多少。"),
      m("girl", "我买的是确定性。"),
      m("boy", "这个商品暂时缺货。"),
      m("girl", "那我能转赠吗？"),
      m("boy", "只能转给更听话的朋友。"),
      m("girl", "日本这边没有这个选项。"),
      m("boy", "那就升级会员。")
    ]
  },
  {
    id: "viral-fengge-female-fan-private-chat",
    title: "主页访问算不算采访",
    viralRole: "female",
    characterNames: { boy: "峰哥", girl: "成年女粉" },
    characterAvatarIds: { boy: "journey-1986-shaseng" },
    characterVoiceDescriptions: {
      boy: "成熟真实的男性声线，判断笃定，短句下结论后突然反转，生活化、自嘲，像一本正经地解答世间万物"
    },
    prompt: "成年女粉给峰哥发来一份反向采访提纲，第一题就是“为什么连续看我主页 37 次却不说话”；峰哥试图把访问记录解释成样本观察，却发现女粉早已订好双人桌准备现场答辩。",
    nextPrompt: "见面后女粉可以拿出第二份只有一道题的提纲，也可能揭开“37 次访问”其实是她故意设计的观察实验；峰哥要边下结论边意识到，自己才是这次采访的唯一受访者。",
    messages: [
      m("girl", "峰哥，我整理了一份采访提纲。"),
      m("boy", "这是好事。"),
      m("girl", "第一题：你为什么连续看我主页 37 次？"),
      m("boy", "恰恰相反，这不叫看，这叫观察样本。"),
      m("girl", "凌晨两点也做样本观察？"),
      m("boy", "夜间数据更接近真实。"),
      m("girl", "那为什么一条都不点赞？"),
      m("boy", "观察者不能干预样本。"),
      m("girl", "第二题：样本约你吃饭，去不去？"),
      m("boy", "这个问题不成立。"),
      m("girl", "桌我已经订了。"),
      m("boy", "那就成立一半。"),
      m("girl", "双人桌，晚上七点。"),
      m("boy", "双人桌不能说明关系，饭店对空间有自己的安排。"),
      m("girl", "你已经点了确认预约。"),
      m("boy", "这件事，我得到现场看看。"),
      m("girl", "到底看桌，还是看我？"),
      m("boy", "先看菜单，人不能空着肚子上意义。"),
      m("girl", "菜单最后一页写着：采访对象，峰哥。"),
      m("boy", "那你这不是请吃饭，是有备而来。")
    ]
  },
  {
    id: "viral-fengge-male-b-friend-advice",
    title: "到账不算心动",
    viralRole: "male",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "男B友", girl: "峰哥" },
    characterGenders: { boy: "boy", girl: "boy" },
    characterAvatarIds: { girl: "journey-1986-shaseng" },
    characterVoiceDescriptions: {
      girl: "成熟真实的男性声线，判断笃定，短句下结论后突然反转，生活化、自嘲，像一本正经地解答世间万物"
    },
    prompt: "男B友问峰哥，喜欢的女生平时不回消息、收到红包却秒回是不是慢热；峰哥把情感问题分析成支付平台活跃问题。",
    nextPrompt: "男B友可以继续拿聊天截图、朋友圈和见面细节来问诊，也可能突然替朋友问另一个完全不同的人生难题；峰哥的答案要逐步暴露他自己的矛盾。",
    messages: [
      m("boy", "峰哥，她平时不回我，发红包却秒回，是不是慢热？"),
      m("girl", "这是好事。"),
      m("boy", "真有戏？"),
      m("girl", "恰恰相反，她对你没反应，对到账有反应。"),
      m("boy", "那她到底喜不喜欢我？"),
      m("girl", "我跟你说，别研究她，先研究你自己。"),
      m("boy", "我怎么了？"),
      m("girl", "你把转账当聊天，把收款提示当心动。"),
      m("girl", "这不是追人，是给支付平台做活跃。"),
      m("boy", "那我还追吗？"),
      m("girl", "先别上价值，停七天只看她做什么。"),
      m("girl", "她主动找你是关系，只催红包是业务。"),
      m("boy", "听完更难受了。"),
      m("girl", "难受是好事。人一难受，才舍得看事实。"),
      m("boy", "那我到底该问她什么？"),
      m("girl", "别问。你消失七天，行为会替她回答。"),
      m("boy", "要是她真来找我呢？"),
      m("girl", "到时候再看，没发生的事别提前上意义。")
    ]
  },
  {
    id: "viral-luo-jia-next-week-live",
    title: "下周一定进直播间",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "罗永浩", girl: "贾跃亭" },
    characterGenders: { boy: "boy", girl: "boy" },
    prompt: "罗永浩邀请贾跃亭进直播间聊“如何按时交付”，贾跃亭回复“下周一定”，罗永浩把预约时间直接设成了每周循环。",
    nextPrompt: "循环日历开始自动邀请投资人、供应商和直播观众，所有人都在等同一个下周；两人可以争夺主持权，也可以把一场延期变成跨时区发布会。",
    messages: [
      m("boy", "来直播间聊聊按时交付？"),
      m("girl", "下周一定。"),
      m("boy", "具体哪天下周？"),
      m("girl", "下周的下周。"),
      m("boy", "那我把预约设成每周循环。"),
      m("girl", "很好，永远不会错过。"),
      m("boy", "也永远不会到。"),
      m("girl", "你要对未来有耐心。"),
      m("boy", "我直播间不卖未来。"),
      m("girl", "那卖梦想吗？"),
      m("boy", "梦想也得能发货。"),
      m("girl", "我可以先连线。"),
      m("boy", "你人在哪？"),
      m("girl", "去发布会的路上。"),
      m("boy", "哪个发布会？"),
      m("girl", "下周那个。")
    ]
  },
  {
    id: "viral-luo-lei-crossroads-podcast",
    title: "低调上一次十字路口",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "罗永浩", girl: "雷军" },
    characterGenders: { boy: "boy", girl: "boy" },
    characterAvatarIds: { boy: "neutral-animal-orange-cat", girl: "neutral-animal-capybara" },
    prompt: "罗永浩邀请雷军上《十字路口》播客，想聊创业、造车和高光背后的真话。雷军表示自己只想低调聊聊，却不断试探能不能把新车开进录音棚，两人在“不做宣传”和“顺便展示”之间极限拉扯。",
    nextPrompt: "录制当天，雷军真的把新车开到了门口，还带来一份声称“不是发布会流程”的 PPT；罗永浩可以逐页拆穿这场低调宣传，也可以临时加入试驾环节。",
    messages: [
      m("boy", "雷总，来上一次《十字路口》？"),
      m("girl", "可以聊聊，但我最近想低调一点。"),
      m("boy", "放心，我们是长谈，不是发布会。"),
      m("girl", "那能不能聊聊最近开的车？"),
      m("boy", "可以聊你为什么造车。"),
      m("girl", "车最好也在现场，听众比较有感觉。"),
      m("boy", "播客一般靠耳朵感受。"),
      m("girl", "偶尔也可以感受一下零百加速。"),
      m("boy", "你不是要低调吗？"),
      m("girl", "低调地开过去。"),
      m("boy", "车标遮一下？"),
      m("girl", "遮了听众不知道我们在聊哪辆车。"),
      m("boy", "那我们只聊创业的十字路口。"),
      m("girl", "正好，新车有十字路口领航。"),
      m("boy", "你这句已经像口播了。"),
      m("girl", "那剪掉吧。"),
      m("boy", "我怕你录制时再说三遍。"),
      m("girl", "主要是重要的事情值得再说三遍。")
    ]
  },
  {
    id: "viral-liu-qiangdong-passerby",
    title: "离职后成了路人",
    viralRole: "any",
    playerCharacterId: "girl",
    characterAvatarSet: "neutral-editorial",
    characterAvatarIds: { boy: "dragonball-goku-orange" },
    characterNames: { boy: "刘强东", girl: "前员工" },
    characterGenders: { boy: "boy", girl: "boy" },
    prompt: "一位曾经在公司拼过多年的员工离职后问刘强东，自己只是想把生活放在工作前面，为什么就从“兄弟”变成了“路人”；刘强东把那段关于生活选择、拼搏和兄弟的经典判断完整说给他听。",
    nextPrompt: "前员工可以拿出过去五年的加班记录，追问曾经一起拼过的日子是否会因离职清零；也可以让仍在职的老同事加入对话，讨论“兄弟”到底是一种感情、绩效标准，还是只在共事时有效的身份。",
    messages: [
      m("girl", "东哥，我离职后看到了你说“不是兄弟，是路人”那段。"),
      m("boy", "我也知道每个人生活的选择不一样。"),
      m("boy", "我们也有员工，他其实更多在享受生活。"),
      m("boy", "生活第一，事业、工作第二，不想拼，我能理解。"),
      m("boy", "这是每个人的选择，都是不一样的，你没有错。"),
      m("girl", "既然我没有错，为什么就不算兄弟了？"),
      m("boy", "但我只能说，你不是我们的兄弟，你是路人。"),
      m("girl", "什么叫路人？"),
      m("boy", "就是你既不是我的朋友，也不是我的兄弟，也不是我的敌人。"),
      m("boy", "我们不是一路人，我们不是一家人。"),
      m("boy", "我们不应该在一起共事。"),
      m("boy", "因为你的存在，会让我们在拼搏的兄弟们的利益严重受损。"),
      m("boy", "对他们严重不公平。"),
      m("girl", "可我在公司五年，也拼过，也熬过夜。"),
      m("boy", "我知道，所以我说你没有错。"),
      m("girl", "那我离开的那一天，过去五年就都不算一路了？"),
      m("boy", "路是不是同一条，要看现在往哪走。"),
      m("girl", "可你说兄弟的时候，从来没说这个称呼有离职日期。"),
      m("boy", "这也是你的选择。"),
      m("girl", "不，这是我的问题。你还没有回答。")
    ]
  },
  {
    id: "viral-daughter-kingdom-520",
    title: "返程导航泄露了",
    viralRoles: ["male", "female"],
    characterNames: { boy: "唐玄奘", girl: "女儿国国王" },
    characterAvatarIds: { boy: "journey-1986-tang", girl: "journey-1986-queen" },
    prompt: "女儿国国王收到唐僧共享的取经导航，发现“成佛后的返程终点”被设成女儿国，备注还是“不带徒弟”；唐僧坚持说是系统自动规划，女王便顺手替他预订了御花园双人席。",
    nextPrompt: "悟空突然申请加入共享导航，女王可以公开返程备注，唐僧也可以抢先修改路线；下一段还能从御花园预约、通关文牒婚姻栏或八戒发现截图继续制造误会。",
    messages: [
      m("girl", "御弟哥哥，你共享的取经导航我收到了。"),
      m("boy", "陛下可随时查看贫僧西行进度。"),
      m("girl", "我看见了，终点是灵山。"),
      m("boy", "正是。"),
      m("girl", "可下面还有一行：成佛后返程。"),
      m("boy", "导航自动规划，不必当真。"),
      m("girl", "返程终点为什么是女儿国？"),
      m("boy", "许是系统根据历史停留时长推荐。"),
      m("girl", "备注又为什么是“不带徒弟”？"),
      m("boy", "悟空他们不喜故地重游。"),
      m("girl", "那你喜欢？"),
      m("boy", "出家人对路线没有偏好。"),
      m("girl", "好，我把御花园终身席取消了。"),
      m("boy", "倒也不必浪费公共资源。"),
      m("girl", "那改成双人席。"),
      m("boy", "贫僧觉得还是取消妥当。"),
      m("girl", "来不及了，预约人写的是唐玄奘。"),
      m("boy", "能否改成玄奘一行？"),
      m("girl", "可以，另一行写女儿国国王。"),
      m("boy", "陛下这导航，比妖怪还会绕。")
    ]
  },
  {
    id: "viral-baigujing-third-account",
    title: "三打售后只算一单",
    viralRoles: ["male", "female"],
    characterNames: { boy: "孙悟空", girl: "白骨精" },
    characterAvatarIds: { boy: "journey-1986-wukong", girl: "journey-1986-baigujing" },
    prompt: "白骨精建立“三打售后群”投诉孙悟空：自己换了三套造型挨了三棒，天庭战绩却只给悟空算一单；孙悟空以售后客服身份进群，发现她真正要求的不是赔偿，而是补一次正式见面。",
    nextPrompt: "白骨精可以把三次变装的原图发进群要求重新判定，悟空也可能发现所谓“第四次补打”被预约在一家餐厅；下一段可从售后仲裁、八戒误入群或两人的线下验收继续。",
    messages: [
      m("girl", "你好，我要投诉孙悟空。"),
      m("boy", "老孙就是，投诉内容？"),
      m("girl", "我换了三套造型，挨了三棒，你战绩怎么只算一单？"),
      m("boy", "同一妖精重复下单，系统自动合并。"),
      m("girl", "少女、老妇、老翁，哪里同一件商品？"),
      m("boy", "包装不同，骨架编号一样。"),
      m("girl", "你打之前扫描过？"),
      m("boy", "火眼金睛支持隔空验货。"),
      m("girl", "那为什么第三次才喊我名字？"),
      m("boy", "前两次没看详情页。"),
      m("girl", "我要申请三次独立战绩。"),
      m("boy", "可以，得重新验收。"),
      m("girl", "第四次还打？"),
      m("boy", "售后流程不能少。"),
      m("girl", "行，我把验收地点发你。"),
      m("boy", "怎么是家餐厅？"),
      m("girl", "公共场合，防止你掏棒子。"),
      m("boy", "备注为什么写双人位？"),
      m("girl", "三次售后，一顿结清。"),
      m("boy", "老孙第一次见妖怪主动约验收。"),
      m("girl", "不然怎么证明你每次都认得出我？")
    ]
  },
  {
    id: "viral-journey-secret-cp-group",
    title: "取经项目总群",
    chatMode: "group",
    viralRole: "any",
    presetCharacters: [
      {
        id: "wukong",
        name: "孙悟空",
        side: "right",
        avatarGender: "boy",
        avatarId: "journey-1986-wukong",
        voiceDescription: "机敏利落的成年男性声线，压着火气，嘴硬但会下意识护着白骨精"
      },
      {
        id: "baigujing",
        name: "白骨精",
        side: "left",
        avatarGender: "girl",
        avatarId: "journey-1986-baigujing",
        voiceDescription: "清醒锋利的成年女性声线，表面疏离，和孙悟空对话时暗藏熟稔与调侃"
      },
      {
        id: "tang",
        name: "唐玄奘",
        side: "left",
        avatarGender: "boy",
        avatarId: "journey-1986-tang",
        voiceDescription: "温和克制的成年男性声线，认真维护群规，却经常最后才看懂气氛"
      },
      {
        id: "queen",
        name: "女儿国国王",
        side: "left",
        avatarGender: "girl",
        avatarId: "journey-1986-queen",
        voiceDescription: "从容清亮的成年女性声线，温柔里带判断，最先看破别人没有说出口的关系"
      },
      {
        id: "shaseng",
        name: "沙僧",
        side: "left",
        avatarGender: "boy",
        avatarId: "journey-1986-shaseng",
        voiceDescription: "沉稳朴实的成年男性声线，发言不多，但总能补上最关键的一条证据"
      },
      {
        id: "bajie",
        name: "猪八戒",
        side: "left",
        avatarGender: "boy",
        avatarId: "journey-1986-bajie",
        voiceDescription: "活泼圆润的成年男性声线，八卦敏锐，喜欢把大家不敢说的话直接点破"
      }
    ],
    prompt: "唐僧建了“取经项目总群”，开场只有师徒四人讨论今日行程。八戒忽然发现群成员显示六人，还直接 cue 了女儿国国王和白骨精；两位一直潜水的人先后突然开口，并从悟空和白骨精过分熟悉的语气里撞破一条秘密关系线。",
    nextPrompt: "八戒可以另建“师父看不见的小群”复盘两位潜水成员为何早就在群里，女王也可以晒出入群时间继续追问；下一段还可从悟空抢着改群名、白骨精误发昨晚截图或唐僧清查邀请记录展开。",
    messages: [
      m("tang", "新建群，今日行程都在这里说。"),
      m("bajie", "师父，群名为什么叫项目总群？"),
      m("wukong", "因为有人走两步就要汇报。"),
      m("shaseng", "大师兄说的是二师兄。"),
      m("bajie", "我那是随时同步取经风险。"),
      m("tang", "好了，先确认今晚住处。"),
      m("bajie", "等等，我们师徒四人，群成员怎么显示六个？"),
      m("shaseng", "确实六个，有两个一直没说话。"),
      m("wukong", "可能是系统算上了坐骑。"),
      m("bajie", "白龙马的微信名叫女儿国国王？"),
      m("tang", "为师只邀请了你们三个。"),
      m("bajie", "那另一个白骨精是谁拉的？"),
      m("bajie", "@女儿国国王 @白骨精 两位潜水的，出来走两步。"),
      m("wukong", "呆子，别在群里乱 cue 人。"),
      m("queen", "本王一直在，只是想听御弟哥哥怎么解释群成员。"),
      m("tang", "陛下何时进来的？"),
      m("queen", "比你发第一条消息早一点。"),
      m("baigujing", "我也在。猴子刚才说谁是系统算进来的？"),
      m("wukong", "老孙没说你。"),
      m("baigujing", "你连我什么时候进群都知道，还说不熟？"),
      m("wukong", "群管理看得见。"),
      m("baigujing", "昨晚你不是这么说的。"),
      m("baigujing", "发错群了。"),
      m("shaseng", "大师兄，你们昨晚还有另一个群？"),
      m("bajie", "我建个小群复盘，师父别进。"),
      m("tang", "为师已经看见了。"),
      m("queen", "小群拉我，我知道她们为什么在大群。"),
      m("wukong", "都别乱拉，先查是谁建的群。"),
      m("baigujing", "你急什么？群不是你昨晚建的吗？"),
      m("bajie", "懂了，师父只是今天才被拉进来。")
    ]
  },
  {
    id: "viral-gta-release-city-summit",
    title: "全城等 GTA VI",
    chatMode: "group",
    viralRole: "any",
    presetCharacters: [
      {
        id: "lucia",
        name: "Lucia",
        side: "right",
        avatarGender: "girl",
        avatarId: "gta-lucia",
        voiceDescription: "果断自信的成年拉丁裔女性声线，语速利落，习惯把空想迅速变成计划"
      },
      {
        id: "jason",
        name: "Jason",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-jason",
        voiceDescription: "松弛又警觉的成年男性声线，带海岸生活气息，嘴上怕麻烦却总跟着 Lucia 行动"
      },
      {
        id: "michael",
        name: "Michael",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-michael",
        voiceDescription: "疲惫、讲究又带讽刺感的中年男性声线，习惯从家庭和心理咨询角度分析犯罪"
      },
      {
        id: "franklin",
        name: "Franklin",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-franklin",
        voiceDescription: "冷静务实的年轻男性声线，熟悉车辆、生意和洛圣都街头规则，总能给出可执行建议"
      },
      {
        id: "trevor",
        name: "Trevor",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-trevor",
        voiceDescription: "粗粝高能的中年男性声线，情绪切换很快，把任何闲聊都能拐向爆炸和荒野生存"
      },
      {
        id: "niko",
        name: "Niko",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-niko",
        voiceDescription: "低沉克制的东欧成年男性声线，对所谓美国梦保持冷幽默，发言简短但一针见血"
      },
      {
        id: "cj",
        name: "CJ",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-cj",
        voiceDescription: "自然直接的年轻男性声线，重视家人、街区与兄弟，总能把宏大计划落回吃饭和回家"
      },
      {
        id: "tommy",
        name: "Tommy",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-tommy",
        voiceDescription: "自信强势的成年男性声线，带八十年代迈阿密式派头，对 Vice City 的审美拥有绝对话语权"
      },
      {
        id: "claude",
        name: "Claude",
        side: "left",
        avatarGender: "boy",
        avatarId: "gta-claude",
        voiceDescription: "几乎从不开口的沉默成年男性角色，只用极短文字、标点和定位表达态度"
      }
    ],
    prompt: "GTA VI 确认将在 2026 年 11 月 19 日发布，Lucia 和 Jason 建了一个跨城市群，邀请 Michael、Franklin、Trevor、Niko、CJ、Tommy 和 Claude 闲聊。来自 Vice City、Los Santos、Liberty City 与荒漠的老主角们互相调侃各自的生活方式，还一本正经地竞猜新作会从哪次倒霉的小买卖开始。",
    nextPrompt: "群里可以继续竞猜 GTA VI 的第一项任务、双主角分工和谁会最先背叛谁，也可以让众人晒出各自城市的生活守则；下一段可从 Lucia 发来一张神秘地图、Claude 突然共享定位或 Trevor 宣布提前去 Leonida 踩点展开。",
    messages: [
      m("lucia", "11 月 19 日，Leonida 见。先说好，谁都别替我们猜结局。"),
      m("jason", "她的意思是可以猜开场，但猜错了别怪我们。"),
      m("michael", "双主角、共同生活、一次简单差事出错。我猜开场先抢银行，结尾一起看心理医生。"),
      m("franklin", "你为什么觉得每座城市都需要你的心理医生？"),
      m("michael", "因为有些人住沙漠，开飞机来参加家庭聚会。"),
      m("trevor", "那叫保持关系。你住豪宅，见家人还得预约。"),
      m("cj", "先别吵。新城市第一件事应该找家像样的汉堡店。"),
      m("niko", "在 Liberty City，第一件事是发现表哥描述的豪宅并不存在。"),
      m("tommy", "在 Vice City，第一件事是换掉你们那些灰外套。城市有霓虹，人也要配合。"),
      m("claude", "……"),
      m("franklin", "Claude 说 Liberty City 下雨，穿深色耐脏。"),
      m("claude", "✓"),
      m("lucia", "所以你们猜 GTA VI 开场是什么？"),
      m("cj", "一顿饭被人打断，然后被迫绕全城跑腿。经典。"),
      m("franklin", "我猜是辆看起来很贵、实际装着麻烦的车。"),
      m("michael", "我猜 Jason 说“最后一票”，Lucia 根本没信。"),
      m("jason", "我从来没说最后一票。"),
      m("lucia", "因为他每次都说“很快回来”。"),
      m("niko", "这就是美国梦的精简版本。"),
      m("trevor", "都太保守。我猜开场有快艇、鳄鱼和一架不该起飞的飞机。"),
      m("tommy", "只要别把八十年代的 Vice City 拍得太朴素。"),
      m("lucia", "放心，现在的人会先直播，再逃跑。"),
      m("franklin", "Los Santos 也这样，只是逃跑前先看流量。"),
      m("cj", "我们那时候讲街区。"),
      m("michael", "我们这时候讲资产配置。"),
      m("trevor", "我讲生存。资产烧完了，人还在就算盈利。"),
      m("niko", "Liberty City 讲冬天。车还没发动，人生已经开始后悔。"),
      m("tommy", "Vice City 讲衬衫。穿对了，麻烦看起来也像度假。"),
      m("jason", "Leonida 讲什么？"),
      m("lucia", "讲谁认识谁，谁手里有什么，以及出事以后谁还站在你旁边。"),
      m("claude", "📍"),
      m("franklin", "他突然发定位了。"),
      m("trevor", "很好，提前踩点小组成立。"),
      m("lucia", "谁敢提前来，我就把谁写进支线任务。")
    ]
  },
  {
    id: "viral-office-private-calendar",
    title: "会议邀请只发给了你",
    viralRoles: ["male", "female"],
    prompt: "女主发现男同事把本该群发的加班会议邀请只发给了她，地点却写着公司楼下新开的咖啡店。",
    nextPrompt: "两人可以把这场假会议演给同事看，也可能被老板临时加入日历；下一段可从办公室起哄、方案泄露或一次没说出口的约会继续。",
    messages: [
      m("girl", "你会议邀请发错人了。"),
      m("boy", "没发错。"),
      m("girl", "参会人怎么只有我？"),
      m("boy", "小范围评审。"),
      m("girl", "地点为什么是咖啡店？"),
      m("boy", "公司会议室满了。"),
      m("girl", "晚上九点也满？"),
      m("boy", "那是会后时间。"),
      m("girl", "议题写着了解彼此。"),
      m("boy", "协作前置调研。"),
      m("girl", "需要我准备什么？"),
      m("boy", "别带电脑。"),
      m("girl", "那我带结论。"),
      m("boy", "什么结论？"),
      m("girl", "会议可以开，别装加班。")
    ]
  },
  {
    id: "viral-roommate-last-key",
    title: "备用钥匙只剩一把",
    viralRoles: ["male", "female"],
    prompt: "一对刚认识的男女合租，房东临时说备用钥匙只剩一把，让两人自己决定放在谁那里。",
    nextPrompt: "两人可以制定一套越写越像约会规则的钥匙交接表，也可能发现房东其实留了第三把；后续可走同住试探、深夜忘带钥匙或前租客秘密。",
    messages: [
      m("girl", "房东说备用钥匙只剩一把。"),
      m("boy", "放你那。"),
      m("girl", "你不怕我锁你门外？"),
      m("boy", "你看起来会先发消息。"),
      m("girl", "我们才认识十分钟。"),
      m("boy", "已经比房东可靠了。"),
      m("girl", "那你几点回？"),
      m("boy", "这就开始报备？"),
      m("girl", "我只管钥匙。"),
      m("boy", "十一点前。"),
      m("girl", "超过呢？"),
      m("boy", "请钥匙管理员开门。"),
      m("girl", "收费。"),
      m("boy", "包夜宵吗？"),
      m("girl", "看你敲门态度。")
    ]
  },
  {
    id: "viral-encounter-wrong-umbrella",
    title: "你拿错了我的伞",
    viralRoles: ["male", "female"],
    prompt: "雨夜地铁末班车后，两个陌生男女拿错了彼此的伞，回家才发现伞柄上都挂着同一家旧书店的牌子。",
    nextPrompt: "两人可以约在旧书店交换雨伞，却发现彼此都在找一本绝版书；下一段可从第二次偶遇、书中夹条或有人故意换伞展开。",
    messages: [
      m("boy", "你是不是拿错伞了？"),
      m("girl", "黑色长柄？"),
      m("boy", "伞柄有旧书店牌子。"),
      m("girl", "我的也有。"),
      m("boy", "那怎么证明哪把是谁的？"),
      m("girl", "我的伞骨坏了一根。"),
      m("boy", "我手里这把完好。"),
      m("girl", "那你赚了。"),
      m("boy", "但里面夹了张书单。"),
      m("girl", "别看最后一行。"),
      m("boy", "已经看了。"),
      m("girl", "那本书我找了三年。"),
      m("boy", "我刚好有。"),
      m("girl", "你想怎么换？"),
      m("boy", "先换伞，再谈书。")
    ]
  }
];
