import type { PresetStory } from "./presetStories.js";

type PresetMessage = PresetStory["messages"][number];

const m = (
  roleId: string,
  text: string,
  options: Omit<PresetMessage, "roleId" | "text"> = {}
): PresetMessage => ({ roleId, text, ...options });

export const viralPresetStories: PresetStory[] = [
  {
    id: "viral-pan-jinlian-window-request",
    title: "嫂嫂说家里有虎",
    viralRole: "male",
    characterNames: { boy: "武松", girl: "潘金莲" },
    prompt: "潘金莲给武松发消息，说武大郎今晚卖烧饼不回家，让他千万别上楼，因为家里来了一只会发微信的老虎；武松没有接话，而是把整段聊天同步给了哥哥。",
    nextPrompt: "门外突然响起三次敲门声，潘金莲说是风，武松却收到哥哥发来的实时定位；下一段可以揭开门外是谁、那只“老虎”指谁，或让武大郎直接加入群聊对质。",
    messages: [
      m("girl", "二郎，你哥今晚卖烧饼，不回来了。"),
      m("boy", "哥哥半个时辰前说已经收摊。"),
      m("girl", "他临时又接了个大单。"),
      m("boy", "谁一口气买八十个炊饼？"),
      m("girl", "你先别上楼，家里有老虎。"),
      m("boy", "清河县也有虎？"),
      m("girl", "有，会敲门，还会发微信。"),
      m("boy", "把它微信推给我。"),
      m("girl", "你怎么什么虎都想加好友？"),
      m("boy", "先确认公母，再决定怎么打。"),
      m("girl", "是只公虎，穿得还挺体面。"),
      m("boy", "那不像虎，像客人。"),
      m("girl", "客人更不能让你撞见。"),
      m("boy", "嫂嫂，这段话我转给哥哥了。"),
      m("girl", "你哥现在没空看。"),
      m("boy", "他回了。"),
      m("girl", "回什么？"),
      m("boy", "他说他就在门外，让我问问屋里的虎怕不怕卖烧饼的。"),
      m("girl", "刚才那三声是风。"),
      m("boy", "风又敲了三下。")
    ]
  },
  {
    id: "viral-trump-takaichi-tariff-coupon",
    title: "特朗普的关税优惠券",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "特朗普", girl: "高市早苗" },
    prompt: "特朗普给高市早苗发了一张亲笔签名的“关税优惠券”，高市早苗问他能不能和会员折扣叠加使用。",
    nextPrompt: "高市把优惠券发进多国群聊后意外引来竞价，特朗普开始追查条款是谁泄露的；故事可以走外交拍卖、会员体系失控或假券风波。",
    messages: [
      m("boy", "送你一张最好的关税优惠券。"),
      m("girl", "可以和会员折扣叠加吗？"),
      m("boy", "仅限当面使用。"),
      m("girl", "还要满额吗？"),
      m("boy", "满额才显得优惠。"),
      m("girl", "券上怎么没有截止日期？"),
      m("boy", "谈判结束那天自动过期。"),
      m("girl", "谁决定谈判结束？"),
      m("boy", "我。"),
      m("girl", "那折扣到底是多少？"),
      m("boy", "看你买多少。"),
      m("girl", "我买的是确定性。"),
      m("boy", "这个商品暂时缺货。"),
      m("girl", "那我能转赠吗？"),
      m("boy", "只能转给更听话的朋友。"),
      m("girl", "日本这边没有这个选项。"),
      m("boy", "那就升级会员。")
    ]
  },
  {
    id: "viral-fengge-female-fan-private-chat",
    title: "主页访问算不算采访",
    viralRole: "female",
    characterNames: { boy: "峰哥", girl: "成年女粉" },
    characterAvatarIds: { boy: "journey-1986-shaseng" },
    characterVoiceDescriptions: {
      boy: "成熟真实的男性声线，判断笃定，短句下结论后突然反转，生活化、自嘲，像一本正经地解答世间万物"
    },
    prompt: "成年女粉给峰哥发来一份反向采访提纲，第一题就是“为什么连续看我主页 37 次却不说话”；峰哥试图把访问记录解释成样本观察，却发现女粉早已订好双人桌准备现场答辩。",
    nextPrompt: "见面后女粉可以拿出第二份只有一道题的提纲，也可能揭开“37 次访问”其实是她故意设计的观察实验；峰哥要边下结论边意识到，自己才是这次采访的唯一受访者。",
    messages: [
      m("girl", "峰哥，我整理了一份采访提纲。"),
      m("boy", "这是好事。"),
      m("girl", "第一题：你为什么连续看我主页 37 次？"),
      m("boy", "恰恰相反，这不叫看，这叫观察样本。"),
      m("girl", "凌晨两点也做样本观察？"),
      m("boy", "夜间数据更接近真实。"),
      m("girl", "那为什么一条都不点赞？"),
      m("boy", "观察者不能干预样本。"),
      m("girl", "第二题：样本约你吃饭，去不去？"),
      m("boy", "这个问题不成立。"),
      m("girl", "桌我已经订了。"),
      m("boy", "那就成立一半。"),
      m("girl", "双人桌，晚上七点。"),
      m("boy", "双人桌不能说明关系，饭店对空间有自己的安排。"),
      m("girl", "你已经点了确认预约。"),
      m("boy", "这件事，我得到现场看看。"),
      m("girl", "到底看桌，还是看我？"),
      m("boy", "先看菜单，人不能空着肚子上意义。"),
      m("girl", "菜单最后一页写着：采访对象，峰哥。"),
      m("boy", "那你这不是请吃饭，是有备而来。")
    ]
  },
  {
    id: "viral-fengge-male-b-friend-advice",
    title: "到账不算心动",
    viralRole: "male",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "男B友", girl: "峰哥" },
    characterGenders: { boy: "boy", girl: "boy" },
    characterAvatarIds: { girl: "journey-1986-shaseng" },
    characterVoiceDescriptions: {
      girl: "成熟真实的男性声线，判断笃定，短句下结论后突然反转，生活化、自嘲，像一本正经地解答世间万物"
    },
    prompt: "男B友问峰哥，喜欢的女生平时不回消息、收到红包却秒回是不是慢热；峰哥把情感问题分析成支付平台活跃问题。",
    nextPrompt: "男B友可以继续拿聊天截图、朋友圈和见面细节来问诊，也可能突然替朋友问另一个完全不同的人生难题；峰哥的答案要逐步暴露他自己的矛盾。",
    messages: [
      m("boy", "峰哥，她平时不回我，发红包却秒回，是不是慢热？"),
      m("girl", "这是好事。"),
      m("boy", "真有戏？"),
      m("girl", "恰恰相反，她对你没反应，对到账有反应。"),
      m("boy", "那她到底喜不喜欢我？"),
      m("girl", "我跟你说，别研究她，先研究你自己。"),
      m("boy", "我怎么了？"),
      m("girl", "你把转账当聊天，把收款提示当心动。"),
      m("girl", "这不是追人，是给支付平台做活跃。"),
      m("boy", "那我还追吗？"),
      m("girl", "先别上价值，停七天只看她做什么。"),
      m("girl", "她主动找你是关系，只催红包是业务。"),
      m("boy", "听完更难受了。"),
      m("girl", "难受是好事。人一难受，才舍得看事实。"),
      m("boy", "那我到底该问她什么？"),
      m("girl", "别问。你消失七天，行为会替她回答。"),
      m("boy", "要是她真来找我呢？"),
      m("girl", "到时候再看，没发生的事别提前上意义。")
    ]
  },
  {
    id: "viral-luo-jia-next-week-live",
    title: "下周一定进直播间",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "罗永浩", girl: "贾跃亭" },
    characterGenders: { boy: "boy", girl: "boy" },
    prompt: "罗永浩邀请贾跃亭进直播间聊“如何按时交付”，贾跃亭回复“下周一定”，罗永浩把预约时间直接设成了每周循环。",
    nextPrompt: "循环日历开始自动邀请投资人、供应商和直播观众，所有人都在等同一个下周；两人可以争夺主持权，也可以把一场延期变成跨时区发布会。",
    messages: [
      m("boy", "来直播间聊聊按时交付？"),
      m("girl", "下周一定。"),
      m("boy", "具体哪天下周？"),
      m("girl", "下周的下周。"),
      m("boy", "那我把预约设成每周循环。"),
      m("girl", "很好，永远不会错过。"),
      m("boy", "也永远不会到。"),
      m("girl", "你要对未来有耐心。"),
      m("boy", "我直播间不卖未来。"),
      m("girl", "那卖梦想吗？"),
      m("boy", "梦想也得能发货。"),
      m("girl", "我可以先连线。"),
      m("boy", "你人在哪？"),
      m("girl", "去发布会的路上。"),
      m("boy", "哪个发布会？"),
      m("girl", "下周那个。")
    ]
  },
  {
    id: "viral-lei-yu-joint-launch",
    title: "两场遥遥领先发布会",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "雷军", girl: "余承东" },
    characterGenders: { boy: "boy", girl: "boy" },
    prompt: "雷军和余承东同时给对方发来新品发布会邀请函，备注都写着“欢迎友商到场见证遥遥领先”。",
    nextPrompt: "一个神秘账号又预约了同一分钟的第三场发布会，并同时向两人索要友商席位；他们可以临时结盟查人，也可以把撞车升级成产品擂台。",
    messages: [
      m("boy", "今晚发布会，欢迎友商。"),
      m("girl", "巧了，我也发你一张。"),
      m("boy", "你那张写着遥遥领先。"),
      m("girl", "你这张写着全面领先。"),
      m("boy", "要不一起开？"),
      m("girl", "直播间会放不下。"),
      m("boy", "那你先讲。"),
      m("girl", "友商优先。"),
      m("boy", "我怕你讲完天都亮了。"),
      m("girl", "领先需要一点时间。"),
      m("boy", "那比谁先结束？"),
      m("girl", "可以，输的去对方直播间刷遥遥领先。"),
      m("boy", "奖品呢？"),
      m("girl", "对方新品一台。"),
      m("boy", "我怕你库存不够。"),
      m("girl", "我怕你颜色不够。")
    ]
  },
  {
    id: "viral-liu-qiangdong-passerby",
    title: "你只是路人",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "刘强东", girl: "点外卖的路人" },
    characterGenders: { boy: "boy", girl: "boy" },
    prompt: "一位顾客问刘强东，自己天天点京东外卖算不算兄弟，刘强东看完他的配送记录后回复：“你只是路人，不是我们的兄弟。”",
    nextPrompt: "顾客真的报名做一天骑手，第一单却正好送到刘强东手里；后续可以变成身份互换、兄弟考核，或一次把平台规则逼到角落的现场测试。",
    messages: [
      m("girl", "我天天点京东外卖，算兄弟吗？"),
      m("boy", "你送过外卖吗？"),
      m("girl", "我负责点。"),
      m("boy", "那你只是路人。"),
      m("girl", "优惠券也不算家书？"),
      m("boy", "先亲自送一单再进群。"),
      m("girl", "送一单就算兄弟？"),
      m("boy", "先算见习。"),
      m("girl", "见习有优惠券吗？"),
      m("boy", "有工服。"),
      m("girl", "我只是想点饭。"),
      m("boy", "兄弟不是点出来的。"),
      m("girl", "那我全年订单算什么？"),
      m("boy", "平台流水。"),
      m("girl", "我生日也点了。"),
      m("boy", "骑手准时到，算给你过了。"),
      m("girl", "突然更像路人了。"),
      m("boy", "路人至少不用开早会。")
    ]
  },
  {
    id: "viral-wang-dong-nearby-office",
    title: "离职了还要随时汇报",
    viralRole: "any",
    characterAvatarSet: "neutral-editorial",
    characterNames: { boy: "王自如", girl: "董明珠" },
    prompt: "王自如离职后，董明珠发消息问他那间离自己最近的办公室还留不留，王自如嘴上说不用，听说要给别人又立刻改口。",
    nextPrompt: "新同事搬进那间办公室后发现王自如的旧门禁仍能使用，还留着一份未完成的周报；故事可以继续拉扯汇报关系、旧职位或一场突然召回。",
    messages: [
      m("girl", "你的办公室还留吗？"),
      m("boy", "人都离职了，还留什么。"),
      m("girl", "那我让别人搬进去。"),
      m("boy", "等一下。"),
      m("girl", "不是不留吗？"),
      m("boy", "我只是离职，又没说以后不汇报。"),
      m("girl", "你现在向谁汇报？"),
      m("boy", "向离得最近的人。"),
      m("girl", "你新公司离我十五公里。"),
      m("boy", "高峰期也算近。"),
      m("girl", "那办公室继续给你留着。"),
      m("boy", "租金怎么算？"),
      m("girl", "用周报抵。"),
      m("boy", "我已经离职了。"),
      m("girl", "离职是劳动关系，不是汇报关系。"),
      m("boy", "那门禁呢？"),
      m("girl", "一直没删。")
    ]
  },
  {
    id: "viral-king-of-comedy-support-you",
    title: "演员训练班家属免费",
    viralRole: "any",
    characterNames: { boy: "尹天仇", girl: "柳飘飘" },
    prompt: "尹天仇追着出租车喊出“我养你啊”后，柳飘飘在车上加了他的微信，第一句就问他打算拿什么养。",
    nextPrompt: "柳飘飘发来车费、房租和早餐清单，让尹天仇证明“我养你”不是一句台词；后续可以走现实算账、临时试住，或一场改变两人身份的试镜。",
    messages: [
      m("girl", "你刚刚说什么？"),
      m("boy", "我养你啊。"),
      m("girl", "先把你自己养明白。"),
      m("boy", "那两个人一起省。"),
      m("girl", "怎么省？"),
      m("boy", "演员训练班，家属免费。"),
      m("girl", "你一个月赚多少？"),
      m("boy", "有戏就有。"),
      m("girl", "没戏呢？"),
      m("boy", "教别人演戏。"),
      m("girl", "谁来学？"),
      m("boy", "目前主要是我自己。"),
      m("girl", "那我算家属还是学员？"),
      m("boy", "你想当哪个？"),
      m("girl", "家属要不要考试？"),
      m("boy", "只考一题。"),
      m("girl", "什么？"),
      m("boy", "刚才那句，你信不信。")
    ]
  },
  {
    id: "viral-daughter-kingdom-520",
    title: "返程导航泄露了",
    viralRoles: ["male", "female"],
    characterNames: { boy: "唐玄奘", girl: "女儿国国王" },
    characterAvatarIds: { boy: "journey-1986-tang", girl: "journey-1986-queen" },
    prompt: "女儿国国王收到唐僧共享的取经导航，发现“成佛后的返程终点”被设成女儿国，备注还是“不带徒弟”；唐僧坚持说是系统自动规划，女王便顺手替他预订了御花园双人席。",
    nextPrompt: "悟空突然申请加入共享导航，女王可以公开返程备注，唐僧也可以抢先修改路线；下一段还能从御花园预约、通关文牒婚姻栏或八戒发现截图继续制造误会。",
    messages: [
      m("girl", "御弟哥哥，你共享的取经导航我收到了。"),
      m("boy", "陛下可随时查看贫僧西行进度。"),
      m("girl", "我看见了，终点是灵山。"),
      m("boy", "正是。"),
      m("girl", "可下面还有一行：成佛后返程。"),
      m("boy", "导航自动规划，不必当真。"),
      m("girl", "返程终点为什么是女儿国？"),
      m("boy", "许是系统根据历史停留时长推荐。"),
      m("girl", "备注又为什么是“不带徒弟”？"),
      m("boy", "悟空他们不喜故地重游。"),
      m("girl", "那你喜欢？"),
      m("boy", "出家人对路线没有偏好。"),
      m("girl", "好，我把御花园终身席取消了。"),
      m("boy", "倒也不必浪费公共资源。"),
      m("girl", "那改成双人席。"),
      m("boy", "贫僧觉得还是取消妥当。"),
      m("girl", "来不及了，预约人写的是唐玄奘。"),
      m("boy", "能否改成玄奘一行？"),
      m("girl", "可以，另一行写女儿国国王。"),
      m("boy", "陛下这导航，比妖怪还会绕。")
    ]
  },
  {
    id: "viral-baigujing-third-account",
    title: "三打售后只算一单",
    viralRoles: ["male", "female"],
    characterNames: { boy: "孙悟空", girl: "白骨精" },
    characterAvatarIds: { boy: "journey-1986-wukong", girl: "journey-1986-baigujing" },
    prompt: "白骨精建立“三打售后群”投诉孙悟空：自己换了三套造型挨了三棒，天庭战绩却只给悟空算一单；孙悟空以售后客服身份进群，发现她真正要求的不是赔偿，而是补一次正式见面。",
    nextPrompt: "白骨精可以把三次变装的原图发进群要求重新判定，悟空也可能发现所谓“第四次补打”被预约在一家餐厅；下一段可从售后仲裁、八戒误入群或两人的线下验收继续。",
    messages: [
      m("girl", "你好，我要投诉孙悟空。"),
      m("boy", "老孙就是，投诉内容？"),
      m("girl", "我换了三套造型，挨了三棒，你战绩怎么只算一单？"),
      m("boy", "同一妖精重复下单，系统自动合并。"),
      m("girl", "少女、老妇、老翁，哪里同一件商品？"),
      m("boy", "包装不同，骨架编号一样。"),
      m("girl", "你打之前扫描过？"),
      m("boy", "火眼金睛支持隔空验货。"),
      m("girl", "那为什么第三次才喊我名字？"),
      m("boy", "前两次没看详情页。"),
      m("girl", "我要申请三次独立战绩。"),
      m("boy", "可以，得重新验收。"),
      m("girl", "第四次还打？"),
      m("boy", "售后流程不能少。"),
      m("girl", "行，我把验收地点发你。"),
      m("boy", "怎么是家餐厅？"),
      m("girl", "公共场合，防止你掏棒子。"),
      m("boy", "备注为什么写双人位？"),
      m("girl", "三次售后，一顿结清。"),
      m("boy", "老孙第一次见妖怪主动约验收。"),
      m("girl", "不然怎么证明你每次都认得出我？")
    ]
  },
  {
    id: "viral-journey-secret-cp-group",
    title: "取经项目总群",
    chatMode: "group",
    viralRole: "any",
    presetCharacters: [
      {
        id: "wukong",
        name: "孙悟空",
        side: "right",
        avatarGender: "boy",
        avatarId: "journey-1986-wukong",
        voiceDescription: "机敏利落的成年男性声线，压着火气，嘴硬但会下意识护着白骨精"
      },
      {
        id: "baigujing",
        name: "白骨精",
        side: "left",
        avatarGender: "girl",
        avatarId: "journey-1986-baigujing",
        voiceDescription: "清醒锋利的成年女性声线，表面疏离，和孙悟空对话时暗藏熟稔与调侃"
      },
      {
        id: "tang",
        name: "唐玄奘",
        side: "left",
        avatarGender: "boy",
        avatarId: "journey-1986-tang",
        voiceDescription: "温和克制的成年男性声线，认真维护群规，却经常最后才看懂气氛"
      },
      {
        id: "queen",
        name: "女儿国国王",
        side: "left",
        avatarGender: "girl",
        avatarId: "journey-1986-queen",
        voiceDescription: "从容清亮的成年女性声线，温柔里带判断，最先看破别人没有说出口的关系"
      },
      {
        id: "shaseng",
        name: "沙僧",
        side: "left",
        avatarGender: "boy",
        avatarId: "journey-1986-shaseng",
        voiceDescription: "沉稳朴实的成年男性声线，发言不多，但总能补上最关键的一条证据"
      },
      {
        id: "bajie",
        name: "猪八戒",
        side: "left",
        avatarGender: "boy",
        avatarId: "journey-1986-bajie",
        voiceDescription: "活泼圆润的成年男性声线，八卦敏锐，喜欢把大家不敢说的话直接点破"
      }
    ],
    prompt: "唐僧建了“取经项目总群”，把孙悟空、白骨精、女儿国国王、沙僧和猪八戒都拉进来。白骨精与孙悟空其实早已秘密恋爱，却一直没有公开，两人在大群里故意装不熟，八戒和女王开始从细节里抓证据。",
    nextPrompt: "八戒可以另建“师父看不见的小群”集中复盘证据，白骨精和悟空也可能切进只有两人的秘密小群；下一段可从误发截图、群名暴露或女王突然试探中任选一路。",
    messages: [
      m("tang", "新建群，沿途合作统一在这里说。"),
      m("queen", "御弟哥哥，我也算沿途合作？"),
      m("bajie", "师父，这群业务范围挺广。"),
      m("baigujing", "我只是路过咨询。"),
      m("wukong", "妖怪也做咨询？"),
      m("baigujing", "有些猴子还做风控呢。"),
      m("shaseng", "大师兄，你们像认识。"),
      m("wukong", "不熟。"),
      m("baigujing", "确实不熟，只见过三次。"),
      m("bajie", "三次都记得这么清楚？"),
      m("tang", "悟空，不要在群里审人。"),
      m("queen", "那可以私下审？"),
      m("wukong", "谁要私下审她。"),
      m("baigujing", "昨晚你不是这么说的。"),
      m("baigujing", "发错群了。"),
      m("bajie", "我建个小群，师父别进。"),
      m("tang", "为师已经看见了。"),
      m("shaseng", "我已截图。"),
      m("queen", "小群拉我。"),
      m("wukong", "都别乱拉。"),
      m("baigujing", "你急什么？"),
      m("wukong", "群管理需要秩序。"),
      m("bajie", "懂了，秘密需要秩序。")
    ]
  },
  {
    id: "viral-office-private-calendar",
    title: "会议邀请只发给了你",
    viralRoles: ["male", "female"],
    prompt: "女主发现男同事把本该群发的加班会议邀请只发给了她，地点却写着公司楼下新开的咖啡店。",
    nextPrompt: "两人可以把这场假会议演给同事看，也可能被老板临时加入日历；下一段可从办公室起哄、方案泄露或一次没说出口的约会继续。",
    messages: [
      m("girl", "你会议邀请发错人了。"),
      m("boy", "没发错。"),
      m("girl", "参会人怎么只有我？"),
      m("boy", "小范围评审。"),
      m("girl", "地点为什么是咖啡店？"),
      m("boy", "公司会议室满了。"),
      m("girl", "晚上九点也满？"),
      m("boy", "那是会后时间。"),
      m("girl", "议题写着了解彼此。"),
      m("boy", "协作前置调研。"),
      m("girl", "需要我准备什么？"),
      m("boy", "别带电脑。"),
      m("girl", "那我带结论。"),
      m("boy", "什么结论？"),
      m("girl", "会议可以开，别装加班。")
    ]
  },
  {
    id: "viral-roommate-last-key",
    title: "备用钥匙只剩一把",
    viralRoles: ["male", "female"],
    prompt: "一对刚认识的男女合租，房东临时说备用钥匙只剩一把，让两人自己决定放在谁那里。",
    nextPrompt: "两人可以制定一套越写越像约会规则的钥匙交接表，也可能发现房东其实留了第三把；后续可走同住试探、深夜忘带钥匙或前租客秘密。",
    messages: [
      m("girl", "房东说备用钥匙只剩一把。"),
      m("boy", "放你那。"),
      m("girl", "你不怕我锁你门外？"),
      m("boy", "你看起来会先发消息。"),
      m("girl", "我们才认识十分钟。"),
      m("boy", "已经比房东可靠了。"),
      m("girl", "那你几点回？"),
      m("boy", "这就开始报备？"),
      m("girl", "我只管钥匙。"),
      m("boy", "十一点前。"),
      m("girl", "超过呢？"),
      m("boy", "请钥匙管理员开门。"),
      m("girl", "收费。"),
      m("boy", "包夜宵吗？"),
      m("girl", "看你敲门态度。")
    ]
  },
  {
    id: "viral-encounter-wrong-umbrella",
    title: "你拿错了我的伞",
    viralRoles: ["male", "female"],
    prompt: "雨夜地铁末班车后，两个陌生男女拿错了彼此的伞，回家才发现伞柄上都挂着同一家旧书店的牌子。",
    nextPrompt: "两人可以约在旧书店交换雨伞，却发现彼此都在找一本绝版书；下一段可从第二次偶遇、书中夹条或有人故意换伞展开。",
    messages: [
      m("boy", "你是不是拿错伞了？"),
      m("girl", "黑色长柄？"),
      m("boy", "伞柄有旧书店牌子。"),
      m("girl", "我的也有。"),
      m("boy", "那怎么证明哪把是谁的？"),
      m("girl", "我的伞骨坏了一根。"),
      m("boy", "我手里这把完好。"),
      m("girl", "那你赚了。"),
      m("boy", "但里面夹了张书单。"),
      m("girl", "别看最后一行。"),
      m("boy", "已经看了。"),
      m("girl", "那本书我找了三年。"),
      m("boy", "我刚好有。"),
      m("girl", "你想怎么换？"),
      m("boy", "先换伞，再谈书。")
    ]
  }
];
